### ISSUE TITLE
Can anybody tell me where to change the batch size for the auto_encoder model?

### ISSUE THREAD

**Issue by gittygupta** [jayshah19949596/ASL-Thesis2#2]

**Comment by gittygupta** [comment]
I'm getting a ResourceExhaustError by tf v2.1.0
My GPU : Nvidia GeForce GTX 1650
CUDA v10.1
cuDNN 7.4

**Comment by jayshah19949596** [comment]
@gittygupta,

- You have to change the reduce the number of layers or the input.
- The input size is defined in the file `utility.py`  and number of layers is defined in file `auto_enocder_1.py`.
- The batch size is 1 and it is defined in  the file `utility.py`.
