### ISSUE TITLE
NO MODULE  NAMED :: saved_models/ssd_mobilenet/frozen_inference_graph.pb

### ISSUE THREAD

**Issue by KevinPatel04** [jayshah19949596/ASL-Thesis2#3]
@jayshah19949596 please can you upload this directory or suggest  an  alternative to install this?

**Comment by jayshah19949596** [comment]
@KevinPatel04, 

- frozen_inference_graph.pb is a frozen model which I downloaded somewhere from this repo: https://github.com/tensorflow/models.
- The model is huge and can not be uploaded to github.

**Comment by KevinPatel04** [comment]
@jayshah19949596 Thank you for your help but  I already downloaded the file from a different source. But After executing train autoencoder file I am getting a Keyerror as shown in Figures in attachment.

KeyError: "The name 'encoder/encoded/LeakyRelu/Maximum:0' refers to a Tensor which does not exist. The operation, 'encoder/encoded/LeakyRelu/Maximum', does not exist in the graph."

![Capture](https://user-images.githubusercontent.com/42532908/88768009-11ace880-d198-11ea-8ee6-37aa80b0eac1.PNG)
![Capture1](https://user-images.githubusercontent.com/42532908/88768013-12de1580-d198-11ea-9ea3-ab5e1618025d.PNG)
![Capture2](https://user-images.githubusercontent.com/42532908/88768018-140f4280-d198-11ea-9c9c-8fb1c47ede8b.PNG)

**Comment by KevinPatel04** [comment]
> @KevinPatel04,
> 
> * frozen_inference_graph.pb is a frozen model which I downloaded somewhere from this repo: https://github.com/tensorflow/models.
> * The model is huge and can not be uploaded to github.

Instead of uploading on GitHub can you upload the model files as a zip in google drive  or dropbox and share a download link that might be helpful.

**Comment by jayshah19949596** [comment]
- This error looks like you are running the `train_lstm.py`   file. 
- First you have to run the `train_auto_enocder_1.py`
-  `train_auto_enocder_1.py` will produce a `.pb` file 
- Then you have to run the `train_lstm.py` file. 
-  `train_lstm.py` file uses the `.pb` file produced by `train_auto_enocder_1.py` file as inputs.

**Comment by KevinPatel04** [comment]
Yes I am using `train_bi_lstm.py ` file. But I have already executed `train_auto_encoder_1.py` then also I am getting this error.

**Comment by KevinPatel04** [comment]
Issue Solved!
